// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsGap79VMP4sgVBJhkOmKOjno35rLageQ',
    appId: '1:193316244161:android:2036b842ffed08ae81a240',
    messagingSenderId: '193316244161',
    projectId: 'cecattot-57f40',
    storageBucket: 'cecattot-57f40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6VvIehmhSXD2-H6ywlvVqd97B_5_D-E',
    appId: '1:193316244161:ios:80f1aa6e5a06c8e381a240',
    messagingSenderId: '193316244161',
    projectId: 'cecattot-57f40',
    storageBucket: 'cecattot-57f40.appspot.com',
    iosClientId: '193316244161-0ndl01ua7dppgt36c8sttkca2pciiklp.apps.googleusercontent.com',
    iosBundleId: 'com.cecatto.app',
  );
}
